// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBngYbk7nVDZorFIgcIlAav2bVZqulzT8E',
    appId: '1:909975588780:web:2a128eef1508250882b409',
    messagingSenderId: '909975588780',
    projectId: 'mapa-locais-fllutter',
    authDomain: 'mapa-locais-fllutter.firebaseapp.com',
    storageBucket: 'mapa-locais-fllutter.firebasestorage.app',
    measurementId: 'G-ZTZD935HFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7qHmg-IPGQ9iUZnlv0XqQtLfiYAMj01c',
    appId: '1:909975588780:android:44636c228f579e8682b409',
    messagingSenderId: '909975588780',
    projectId: 'mapa-locais-fllutter',
    storageBucket: 'mapa-locais-fllutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdpYI5rVVCMwmTQZIHE0B7mP6X2j-QIxg',
    appId: '1:909975588780:ios:af3aa65268907b9b82b409',
    messagingSenderId: '909975588780',
    projectId: 'mapa-locais-fllutter',
    storageBucket: 'mapa-locais-fllutter.firebasestorage.app',
    iosBundleId: 'com.example.mapaLocais',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdpYI5rVVCMwmTQZIHE0B7mP6X2j-QIxg',
    appId: '1:909975588780:ios:af3aa65268907b9b82b409',
    messagingSenderId: '909975588780',
    projectId: 'mapa-locais-fllutter',
    storageBucket: 'mapa-locais-fllutter.firebasestorage.app',
    iosBundleId: 'com.example.mapaLocais',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBngYbk7nVDZorFIgcIlAav2bVZqulzT8E',
    appId: '1:909975588780:web:52fa7933ac202dec82b409',
    messagingSenderId: '909975588780',
    projectId: 'mapa-locais-fllutter',
    authDomain: 'mapa-locais-fllutter.firebaseapp.com',
    storageBucket: 'mapa-locais-fllutter.firebasestorage.app',
    measurementId: 'G-6GDJDMP75T',
  );
}
